source "https://rubygems.org"

ruby "2.7.2"

group :development do
  gem "rspec"
  gem "rubocop"
  gem "pry"
  gem "aws-sdk-dynamodb"
  gem "httparty"
  gem "nokogiri"
  gem "dotenv"
  gem 'google-cloud-translate-v2', '~> 0.3.0'
end
